### ISSUE TITLE
Version number incorrect

### ISSUE THREAD

**Issue by splorp** [pedroborges/kirby-meta-tags#1]
Hi Pedro.

Thanks for the update to this plugin, but I noticed that the version number in this file was not updated to match the readme or the package.json files.

https://github.com/pedroborges/kirby-meta-tags/blob/e7804c38f5b77584f19d2b489090a7c8ae79521f/meta-tags.php#L6

**Comment by pedroborges** [comment]
Thanks for reporting that @splorp!

**Comment by splorp** [comment]
You bet!
