### ISSUE TITLE
Kirby 3: template settings override defaults instead of being merged

### ISSUE THREAD

**Issue by LeBenLeBen** [pedroborges/kirby-meta-tags#10]
With the Kirby 3 plugin, there seems to be a difference in how template settings are combined with default settings.

Consider:

```php
c::set('pedroborges.metatags.default', function($page, $site) {
  return [
    'og' => [
      'title' => $page->metatitle(),
      'type' => 'website',
      'site_name' => $site->title(),
      'url' => $page->url(),
      'description' => $page->metadescription(),
      'locale' => explode('.', kirby()->language()->locale())[0],
      'namespace:image' => [...],
    ],
  ];
});
```

Coupled with:

```php
c::set('pedroborges.metatags.templates', function($page) {
  return [
    'project' => [
      'og' => [
        'namespace:image' => [...],
      ],
    ],
  ];
});
```

The `og` tags on a page with a template `project` contains only those defined in the templates settings, not the defaults.

With the Kirby 2 version, the template specific settings used to be merged with the default. Now they seems to simply replace them.

**Comment by pedroborges** [comment]
Thank you for the huge contribution @LeBenLeBen! Just merged you PRs.

**Comment by LeBenLeBen** [comment]
@pedroborges Thank you for your time reviewing and releasing 2.0, much appreciated 🙇

**Comment by pedroborges** [comment]
You are welcome.

I have changed the option name to match the one used in v1.1.1 (with a dash). Update it your config after upgrading:

- `pedroborges.meta-tags.default`
- `pedroborges.meta-tags.templates`
