### ISSUE TITLE
Please Upgrade for Kirby 3 ASAP! 😊

### ISSUE THREAD

**Issue by luxlogica** [pedroborges/kirby-meta-tags#3]

**Comment by splorp** [comment]
Ok, that’s not really an issue … that’s a demand.

**Comment by pedroborges** [comment]
I want to publish the Kirby 3 compatible version early next week.

**Comment by pedroborges** [comment]
@luxlogica and @splorp, please take a look and this [alpha version](https://github.com/pedroborges/kirby-meta-tags/releases/tag/v2.0.0-alpha-1).
