### ISSUE TITLE
K3 version not working with latest beta

### ISSUE THREAD

**Issue by HashandSalt** [pedroborges/kirby-meta-tags#4]
Just tried the plugin in the last PlainKit Beta and it throws an "Illegal offset type in isset or empty" error on line 56 of the plugin.

```
if (isset($templates[$page->template()])) {
```
I tried PHP 7.0, 7.1 and 7.2. Same error.

**Comment by HashandSalt** [comment]
Any ideas?

**Comment by HashandSalt** [comment]
Changing line 56 to the following seemed to fix it...

```
if (isset($templates[$page->template()->name()]))
```

**Comment by LeBenLeBen** [comment]
I confirm I have the same issue with Kirby 3.0.0 final.

@HashandSalt Your fix works but I think you should also change line 57 to include the name.
