### ISSUE TITLE
Tag groups and closures

### ISSUE THREAD

**Issue by bvdputte** [pedroborges/kirby-meta-tags#5]
First: great plugin. Thx!

You state in the readme for tag groups:

> These groups accept string, closure, or array as their values. Being so flexible, the sky is the limit to what you can do with Meta Tags!

Can you provide a working example of that please?

I've tried the following to no avail:

```php
c::set('meta-tags.templates', [
    'article' => function($page, $site) {
            return [
                "title" => "test",
                'og' => [
                    'title' => "test"
                ]
            ];
        },
    'about' => [ /* tags groups */ ],
    'products' => [ /* tags groups */ ],
]);
```
I've tried this on a `article`, but I'm getting the `title` and `og:title` as defined in the `meta-tags.default`. It seems like the array_merge isn't happening?

When using an array instead of a closure it works:

```php
c::set('meta-tags.templates', [
    'article' => [
        "title" => "test",
        'og' => [
            'title' => "test"
        ]
    ],
    'about' => [ /* tags groups */ ],
    'products' => [ /* tags groups */ ],
]);
```

 So either the readme is off, or the closure functionality is failing?

I really need closures to work, as I need template-specific variables in the meta tags which means I cannot "pre-populate" the `meta-tags.templates` array since some variables are only available in specific templates.

**Comment by bvdputte** [comment]
FYI: Seems like replacing [this](https://github.com/pedroborges/kirby-meta-tags/blob/36069647c61578429d7f21611ec79b2e7510613d/src/MetaTags.php#L50) with the following "fixes" it somehow:

```php
if (isset($templates[$page->intendedTemplate()])) {
    $tagsForTemplate = $templates[$page->intendedTemplate()];
    $tagsForTemplate = is_callable($tagsForTemplate) ? $tagsForTemplate($page, site()) : $tagsForTemplate;
    $this->data = a::merge($this->data, $tagsForTemplate);
}
```
It's just an extra test to see if the passed array item is also a closure.

**Comment by pedroborges** [comment]
I apologize for taking so long to review this. I think there's a misunderstanding, but please let me know if you think I'm wrong 😉 

Tag groups are `title`, `meta`, `link`, `og`, and `twitter`. Those work with closure from the beginning. After a while, I realized it would be better to accept a closure on the options. Then I added support for:

```php
<?php

return [
    // other options...
    'pedroborges.meta-tags.templates' => function($page, $site) {
        return [
            'article' => [
                "title" => $page->title(),
                'og' => [
                    'title' => $page->title()
                ],
            ],
            'about' => [ /* tags groups */ ],
            'products' => [ /* tags groups */ ],
        ];
    },
];
```

Is that what you are trying to achieve?

**Comment by bvdputte** [comment]
No problem! I think I'm the one owing an apology tbh...
Upon seeing your sample code I noticed I most probably have implemented it wrong 🙈.

First I tried to implement it as following:
```php
return [
    'article' => function($page, $site) {
        return [
            'og' => [
                'type' => 'article',
                'image' => $page->heroimage()->toFile()->url(),
            ]
        ];
    },
];
```

I've altered my code to your sample code:
```php
return [
    'article' => [
        'og' => [
            'type' => 'article',
            'image' => function($page, $site) {
                if ($img = $page->heroimage()->toFile()) {
                    return $img->url();
                }
                return "";
            }
        ]
    ],
];
```
and now it seems to work, so I think it's intended to work like this. Right?
If it is, you can surely dismiss my PR.
